return {
  -- {COUNTER_INCREMENT, HL_NORMAL, HL_EXTENDED}
  ["{"]           = {1,  true,  true},
  ["}"]           = {-1, true,  true},
  ["("]           = {1,  true,  true},
  [")"]           = {-1, true,  true},
  ["["]           = {1,  true,  true},
  ["]"]           = {-1, true,  true},
  ["[["]          = {1,  true,  true},
  ["]]"]          = {-1, true,  true},
  ["if"]          = {1,  false, true},
  ["for"]         = {1,  false, true},
  ["while"]       = {1,  false, true},
  ["repeat"]      = {1,  false, true},
  ["until"]       = {1,  false, true},
  ["do"]          = {0,  false, true},
  ["function"]    = {1,  false, true},
  ["else+"]       = {-1, false, false},
  ["else"]        = {0,  false, true},
  ["elseif+"]     = {-1, false, false},
  ["elseif"]      = {0,  false, true},
  ["then"]        = {0,  false, true},
  ["parameters+"] = {-1, false, false},
  ["end"]         = {-1, false, true},
}
